library(readr)
library(tidyverse)

# be sure to set the 'working directory'. 
# in R Studio, this is: Session > Set Working Directory > To File Source Location. Make sure all files below are relative to this file location.

coverage_df <- read.delim("SLK19_coverage_1761436509.txt", header = TRUE) #put coverage .txt file name in first argument.
coverage_df$X <- NULL #removes the extra column generated by extra \t characters

#i just renamed the column names (i.e. the 'filenames' of the MS files that are compared) so they are easier to read, but feel free to remove.
colnames(coverage_df)[3] <- "Stu1_3FLAG_DMSO" 
colnames(coverage_df)[4] <- "Stu1_3FLAG_Cdc20_AID"
colnames(coverage_df)[5] <- "Stu1_3FLAG_Benomyl"

#get how many file names there are (i.e. how many columns, minus two).
total_cols <- ncol(coverage_df)
file_ids <- 3:total_cols
max_y <- max(coverage_df[,file_ids])
max_y_rounded_up_to_hundreds <- ceiling(max_y / 100) * 100

residue_count <- nrow(coverage_df)-1
max_x_rounded_down_to_hundreds <- floor(residue_count / 100) * 100

filename <- 'Slk19 - MS coverage - Stu1-3FLAG benomyl.pdf' #the final file name.
title_of_plot <- "Slk19 - MS coverage - Stu1-3FLAG benomyl" #title of plot
font_size <- 8 #this looks small in R but is fine in the output PDF.
y_breaks <- seq(from = 0, to = max_y_rounded_up_to_hundreds, by = 100) #you can change but it looks fine for my MS data.
minor_brk_y <- seq(from = 50, to = (max_y_rounded_up_to_hundreds-50), by = 100)
x_breaks <- c(0)
x_breaks <- c(x_breaks, seq(from = 100, to = max_x_rounded_down_to_hundreds, by = 100))

x_limit = max(coverage_df$site)

#the following block of code runs ggplot2 (part of tidyverse) to generate the plot.
ggplot(coverage_df, aes(x = site, y = Stu1_3FLAG_Benomyl)) + #set the y variable equal to the filename/condition name/column name that you want to make a coverage map for.
  geom_col(fill="#1B559D", color="NA", width=1) +
  labs(x = "AA", y = "PSMs", title=title_of_plot) +
  theme_classic(base_size = font_size) +
  theme(
    
    axis.text.x = element_text(size = font_size-2),
    axis.text.y = element_text(size = font_size-2),
    legend.position = "NONE"
    
  ) + 
  scale_y_continuous(guide = guide_axis(minor.ticks=TRUE), expand=c(0,0), breaks = y_breaks, minor_breaks = minor_brk_y, limits = c(0, max_y_rounded_up_to_hundreds))+
  scale_x_continuous(limits = c(1, residue_count), expand=c(0,0), breaks = x_breaks)

#the following code will export the plot with the set dimensions as a PDF in the folder.
ggsave(filename, device=NULL, scale=1, units='in', width=6.12, height=1.75)
